on:
  pull_request:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-18.04
    name: deploy to production
    steps:
      - name: deploying
        run: echo Deploying to oracle server
