name: dev-deployment
on:
  pull_request:
    branches:
      - development
    types: [closed]

  push:
    branches:
      - development

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEVELOPMENT_PK }}
          known_hosts: "temp"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_DEVELOPMENT }} >> ~/.ssh/known_hosts

      - name: Stopping containers
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} 'sudo docker stop $(sudo docker ps -a -q) && sudo docker rm $(sudo docker ps -a -q) && sudo docker rmi $(sudo docker images -aq | head -3)'

      - name: Deploying certificates
        run: |
          touch cert.key
          touch cert.crt
          touch cert.ca-bundle

          echo "${{ secrets.CERT_KEY }}" > cert.key
          echo "${{ secrets.CERT_CRT }}" > cert.crt
          echo "${{ secrets.CERT_CA_BUNDLE }}" > cert.ca-bundle

      - name: Remove old files
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "rm -rf testregex"

      - name: Clone repository
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "git clone -b development https://github.com/J-Nova/testregex.git"

      - uses: GuillaumeFalourd/setup-rsync@v1.1
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }}:./testregex/server/

      - name: Deployment
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "cd testregex && sudo docker build -t testregex . && sudo docker run -d -p 443:3500 -p 80:3000 testregex"
