name: dev-deployment

on:
  pull_request:
    branches:
      - development
    types: [closed]
  push:
    branches:
      - development

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEVELOPMENT_PK }}
          known_hosts: "temp"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_DEVELOPMENT }} >> ~/.ssh/known_hosts

      - name: Stopping containers
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} 'sudo docker stop $(sudo docker ps -q --filter "name=$testregex" 2>/dev/null) 2>/dev/null || true'

      - name: Deploying certificates
        run: |
          echo "${{ secrets.CERT_KEY }}" > cert.key
          echo "${{ secrets.CERT_CRT }}" > cert.crt
          echo "${{ secrets.CERT_CA_BUNDLE }}" > cert.ca-bundle

      - name: Check if repository exists
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} '[ -d "testregex" ] || echo "not-cloned"'

      - name: Clone or pull repository
        run: |
          REPO_STATUS=$(ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} '[ -d "testregex" ] && echo "cloned" || echo "not-cloned"')
          if [ "$REPO_STATUS" == "not-cloned" ]; then
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "git clone -b development https://github.com/J-Nova/testregex.git"
          else
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "cd testregex && git pull origin development"
          fi

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }}:./testregex/server/

      - name: Deployment
        run: ssh -o ServerAliveInterval=10000 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "cd testregex && sudo docker compose up --build -d"
