name: Deployment
on: 
  pull_request:
    branches:
      - development
    types: [closed]
  
  push:
    branches:
      - development

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEVELOPMENT_PK }}
          known_hosts: "temp"
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_DEVELOPMENT }} >> ~/.ssh/known_hosts

      # - name: Stopping containers
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} 'CONTAINERS=$(sudo docker ps -a -q --format="{{.ID}}") && sudo docker stop $CONTAINERS'

      - name: Stopping containers
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} 'docker ps -q --filter "name=$testregex" | xargs -r docker stop | xargs -r docker rm'

      # - name: Removing containers
      #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} 'CONTAINERS=$(sudo docker ps -a -q --format="{{.ID}}") && sudo docker rm $CONTAINERS'

      - name: Deploying certificates
        run: |
          touch ./webapp/server/cert.key
          touch ./webapp/server/cert.crt
          touch ./webapp/server/cert.ca-bundle
          
          echo "${{ secrets.CERT_KEY }}" > ./webapp/server/cert.key
          echo "${{ secrets.CERT_CRT }}" > ./webapp/server/cert.crt
          echo "${{ secrets.CERT_CA_BUNDLE }}" > ./webapp/server/cert.ca-bundle

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }}:testregex/

      - name: Deployment
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEVELOPMENT }} "cd testregex && sudo docker build -t testregex . && sudo docker run -d -p 443:3000 80:1500 testregex"