name: main-deployment
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deployment:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "temp"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Stopping containers
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo docker stop $(sudo docker ps -q --filter "name=$testregex" 2>/dev/null) 2>/dev/null || true'

      - name: Deploying certificates
        run: |
          echo "${{ secrets.CERT_KEY }}" > cert.key
          echo "${{ secrets.CERT_CRT }}" > cert.crt
          echo "${{ secrets.CERT_CA_BUNDLE }}" > cert.ca-bundle

      - name: Check if repository exists
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '[ -d "testregex" ] || echo "not-cloned"'

      - name: Clone or pull repository
        run: |
          REPO_STATUS=$(ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '[ -d "testregex" ] && echo "cloned" || echo "not-cloned"')
          if [ "$REPO_STATUS" == "not-cloned" ]; then
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "git clone -b main https://github.com/J-Nova/testregex.git"
          else
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd testregex && git pull --all && git checkout main && git reset --hard origin/main"
          fi
      - name: Deploy certificates
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:./testregex/server/

      - name: Deployment
        run: ssh -o ServerAliveInterval=1000 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd testregex && sudo docker compose up --build -d"
